-- ESERCIZIO N.1 - SELEZIONA TUTTI GLI OSPITI CHE SONO STATI IDENTIFICATI CON LA CARTA D'IDENTITA'
SELECT * 
FROM `ospiti` 
WHERE `document_type`="CI";

-- ESERCIZIO N.2 - SELEZIONA TUTTI GLI OSPITI CHE SONO NATI DOPO IL 1988
SELECT * 
FROM `ospiti` 
WHERE YEAR(`date_of_birth`)>1988;

-- ESERCIZIO N.3 - SELEZIONA TUTTI GLI OSPITI CHE HANNO PIU' DI 20 ANNI(AL MOMENTO DELL'ESECUZIONE DELLA QUERY)
SELECT * 
FROM `ospiti`
WHERE `date_of_birth` <= SUBDATE(CURRENT_DATE, INTERVAL 20 YEAR);

-- ESERCIZIO N.4 - SELEZIONA TUTTI GLI OSPITI IL CUI NOME INIZIA CON LA D
SELECT * 
FROM `ospiti`
WHERE `name`LIKE "D%";

-- ESERCIZIO N.5 - CALCOLA IL TOTALE INCASSATO DEGLI ORDINI ACCEPTED
SELECT SUM(`price`)
FROM `pagamenti`
WHERE `status`= "accepted";

-- ESERCIZIO N.6 - QUAL E' IL PREZZO MASSIMO PAGATO?
SELECT MAX(`price`) 
FROM `pagamenti`;

-- ESERCIZIO N.7 - SELEZIONA GLI OSPITI RICONOSCIUTI CON PATENTE E NATI NEL 1975
SELECT * 
FROM `ospiti` 
WHERE `document_type`="Driver License" AND YEAR (date_of_birth) ="1975";

-- ESERCIZIO N.8 - QUANTI PAGANTI SONO ANCHE OSPITI?
SELECT COUNT(*)
FROM `paganti`
WHERE `ospite_id` <> "null";  

-- ESERCIZIO N.9 - QUANTI POSTI LETTO HA L'HOTEL IN TOTALE?
SELECT SUM(`beds`)
FROM `stanze`
